#!/bin/sh

set -e

../../bin/python setup.py extract_messages
../../bin/python setup.py update_catalog
../../bin/python setup.py compile_catalog

#../../bin/pybabel extract -F mapping.plone euphorie -o euphorie/deployment/locales/plone.pot
#../../bin/zopepy setup.py update_catalog -i euphorie/deployment/locales/plone.pot --domain plone
#../../bin/zopepy setup.py compile_catalog --domain plone
